### ISSUE TITLE
增加支持计算自定义经验值

### ISSUE THREAD

**Issue by LostXine** [poooi/plugin-exp-calculator#18]
### 需求背景
活动图里面经验值不固定的，有时候直接输入计算可能会更方便。
### 可能的方案
在海图选项里面增加自定义经验功能，有新的输入栏供用户输入经验值。

如果认为这个需求没问题，我可以尝试增加这个功能，谢谢~

**Comment by KagamiChan** [comment]
added via #19 
非常感谢
