### ISSUE TITLE
战斗结果自动变成S

### ISSUE THREAD

**Issue by sgqy** [poooi/plugin-exp-calculator#21]
Ver 3.3.0

比如说使用瞪眼流时要选D。
但回港时计算结果自动变成S。

**Comment by KagamiChan** [comment]
嗯（咕咕咕）

**Comment by KagamiChan** [comment]
确切地说是经验计算结果会变成 S 胜的计算

**Comment by KagamiChan** [comment]
看了一下好还好比较明显，否则估计得拖到重构之后了 - -
b1a6aa6c82a0bb5f511cf07e26410a7f65a99fee
