### ISSUE TITLE
用户设定的目标等级，会在刷新后重置

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-exp-calculator#5]
比如我想把太太肝到80级，手动设定目标等级为80
然后在每次获得经验之后就会被重新设到99。

**Comment by Chibaheit** [comment]
这是动态去查询的...难道保留更好?

**Comment by dkwingsmt** [comment]
“目标等级”还是不要刷新吧……还是说添加一个选项框。如果不选上的话就只以下一次改造等级为准，并且不许改。选上的话就可以改但是不要刷新。
否则目标等级几乎总是会被立即刷新掉，这个插件的意义就……少了一半了……

**Comment by vuryleo** [comment]
和 @dkwingsmt 讨论了一发，是否可以列出所有待改造等级，然后再附加一个手动框？
