### ISSUE TITLE
根據船的下一個改造等級進行顯示

### ISSUE THREAD

**Issue by vuryleo** [poooi/plugin-exp-calculator#8]
很難一句話描述。
例如我想肝一個蒼龍改二，然而並不想在30級將其改成蒼龍改增加消耗，於是其等級可能超過了一改等級（30），此時插件會自動顯示目標等級爲99而非改二的78。

**Comment by dkwingsmt** [comment]
附个议~之前肝 bsm 的时候也遇到了。

**Comment by vuryleo** [comment]
fixed with 5f0c12691e32fb660b857c6049c27ff0caa66443
